spring:

  docker:
    compose:
      enabled: true
      file: src/main/docker/compose.yaml
      lifecycle-management: start_only

  jpa:
    properties:
      hibernate:
        default_schema: public

  liquibase:
    enabled: true
    change-log: db/changelog/master.yaml

server:
  ssl:
    enabled: true
    key-store: classpath:ssl/mykeystore.p12
    key-store-type: PKCS12
    key-store-password: mypassword
    key.alias: mykey
  port: 8443