spring:

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/samurai?autoReconnect=true"&"useSSL=false
    username: samurai
    password: password

  docker:
    compose:
      enabled: true
      file: compose.yaml
      lifecycle-management: start_only

  jpa:
    properties:
      hibernate:
        default_schema: public

  liquibase:
    enabled: true
    change-log: db/changelog/master.yaml

server:
  ssl:
    enabled: true
    key-store: classpath:ssl/mykeystore.p12
    key-store-type: PKCS12
    key-store-password: mypassword
    key-alias: mykey
  port: 8443