spring:

  docker:
    compose:
      enabled: true
      file: src/main/docker/compose.yaml
      lifecycle-management: start_only

  jpa:
    properties:
      hibernate:
        default_schema: public

  liquibase:
    enabled: true
    change-log: db/changelog/master.yaml

server:
  port: 8443